CONTIKI_PROJECT = sensor-node
all: $(CONTIKI_PROJECT)

CONTIKI = ../../contiki-ng

include $(CONTIKI)/Makefile.dir-variables
MODULES += $(CONTIKI_NG_SERVICES_DIR)/shell

include $(CONTIKI)/Makefile.include
